"""Build router training rows from trusted code-query pairs.

The route label is a rubric label for the minimum capable model tier:

- light: cheap/fast model should usually handle it.
- medium: balanced model is the minimum safe choice.
- heavy: strong reasoning model is needed.

Signal vectors are generated by the existing query/code extractors and routing
feature builder. They are not hand-assigned by this script.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import re
from collections import Counter
from pathlib import Path

from code_signals import extract_all
from query_signals import extract_query_signals
from routing.features import build_routing_features


ROUTE_LABELS = ("light", "medium", "heavy")
CONCERNS = {
    "correctness",
    "maintainability",
    "performance",
    "reliability",
    "security",
    "concurrency",
}


def read_csv(path: Path) -> list[dict]:
    with path.open(encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: list[dict]) -> None:
    if not rows:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = list(rows[0])
    seen = set(fieldnames)
    for row in rows[1:]:
        for field in row:
            if field not in seen:
                fieldnames.append(field)
                seen.add(field)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, restval="0")
        writer.writeheader()
        writer.writerows(rows)


def write_jsonl(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=False) + "\n")


def parse_concerns(value: str) -> set[str]:
    try:
        parsed = json.loads(value)
    except json.JSONDecodeError:
        return set()
    return {item for item in parsed if item in CONCERNS}


def code_stat(code: str) -> dict[str, int]:
    lines = [
        line for line in code.splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]
    return {
        "sloc_text": len(lines),
        "chars": len(code),
    }


def label_route(row: dict) -> dict:
    """Assign minimum-capable route label from trusted labels and raw text.

    This intentionally avoids using generated classifier probabilities so the
    route label remains a separate supervision target.
    """
    operation = row["query_operation"]
    domain = row["query_domain"]
    concerns = parse_concerns(row["query_concerns"])
    query = row["query"].casefold()
    stats = code_stat(row["code"])
    reasons = []
    score = 0

    if operation == "explain":
        score += 0
        reasons.append("explain_request")
    elif operation == "generate":
        score += 1
        reasons.append("generation_request")
    elif operation in {"debug", "review", "refactor"}:
        score += 2
        reasons.append(f"{operation}_requires_care")
    elif operation == "optimize":
        score += 2
        reasons.append("optimization_requires_behavior_preservation")

    if concerns & {"security", "concurrency", "reliability"}:
        score += 2
        reasons.append(
            "risk_concern:"
            + ",".join(sorted(concerns & {"security", "concurrency", "reliability"}))
        )
    if "correctness" in concerns:
        score += 1
        reasons.append("correctness_constraint")
    if "performance" in concerns and operation == "optimize":
        score += 1
        reasons.append("performance_optimization")

    if domain in {"security_crypto", "concurrency", "systems_programming"}:
        score += 1
        reasons.append(f"subtle_domain:{domain}")

    if stats["sloc_text"] > 120 or stats["chars"] > 7000:
        score += 2
        reasons.append("large_code_context")
    elif stats["sloc_text"] > 45 or stats["chars"] > 2500:
        score += 1
        reasons.append("moderate_code_context")

    if re.search(
        r"\b("
        r"intermittent|flaky|race|deadlock|cancellation|partial failure|"
        r"memory leak|security|vulnerab|exploit|corrupt|data loss|"
        r"without changing|preserving|contract|regression|edge case"
        r")\b",
        query,
    ):
        score += 1
        reasons.append("subtle_or_constrained_language")

    if operation == "explain" and not (
        concerns & {"security", "concurrency", "reliability"}
    ) and stats["sloc_text"] <= 45:
        label = "light"
    elif score >= 6:
        label = "heavy"
    elif score >= 2:
        label = "medium"
    else:
        label = "light"

    # Borderline examples are valuable but should carry lower sample weight.
    if label == "light":
        secondary = "medium" if score >= 1 else ""
        distance = 2 - score
    elif label == "medium":
        lower_gap = score - 2
        upper_gap = 6 - score
        secondary = "heavy" if upper_gap <= lower_gap else "light"
        distance = min(lower_gap, upper_gap)
    else:
        secondary = "medium" if score <= 7 else ""
        distance = score - 6

    confidence = max(0.55, min(0.95, 0.66 + 0.07 * max(distance, 0)))
    ambiguous = confidence < 0.75
    return {
        "route_label": label,
        "route_label_confidence": round(confidence, 3),
        "secondary_route_label": secondary,
        "route_label_ambiguous": ambiguous,
        "route_label_score": score,
        "route_label_reason": ";".join(reasons),
    }


def route_label_id(label: str) -> int:
    return ROUTE_LABELS.index(label)


def sample_weight(label_info: dict) -> float:
    confidence = float(label_info["route_label_confidence"])
    return round(0.5 + 0.5 * confidence, 4)


def flatten_features(values: dict[str, float]) -> dict[str, float]:
    return {
        f"feature.{name}": round(float(value), 8)
        for name, value in sorted(values.items())
        if ".ambiguity_reason." not in name
        if isinstance(value, (int, float)) and math.isfinite(float(value))
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input",
        type=Path,
        default=Path(
            "router_pair_data/trusted_v1/"
            "llm_grounded_pairs_trusted_v1_with_code_domains.csv"
        ),
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("router_training_data/trusted_v1"),
    )
    parser.add_argument("--progress-every", type=int, default=250)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    rows = read_csv(args.input)
    output_rows = []
    query_cache = {}
    code_cache = {}
    for index, row in enumerate(rows, 1):
        query = row["query"]
        family_id = row["family_id"]
        query_signals = query_cache.get(query)
        if query_signals is None:
            query_signals = extract_query_signals(query)
            query_cache[query] = query_signals
        code_signals = code_cache.get(family_id)
        if code_signals is None:
            code_signals = extract_all(row["code"])
            code_cache[family_id] = code_signals
        features = build_routing_features(
            query_signals,
            code_signals,
            query=query,
            code=row["code"],
        )
        label_info = label_route(row)
        output_row = {
            "pair_id": row["pair_id"],
            "family_id": row["family_id"],
            "split": row["split"],
            "source": row["source"],
            "repository": row.get("repository", ""),
            "file_path": row.get("file_path", ""),
            "function_name": row.get("function_name", ""),
            "query_operation_label": row["query_operation"],
            "query_domain_label": row["query_domain"],
            "query_concerns_label": row["query_concerns"],
            "route_label": label_info["route_label"],
            "route_label_id": route_label_id(label_info["route_label"]),
            "route_label_confidence": label_info["route_label_confidence"],
            "route_label_sample_weight": sample_weight(label_info),
            "secondary_route_label": label_info["secondary_route_label"],
            "route_label_ambiguous": int(label_info["route_label_ambiguous"]),
            "route_label_score": label_info["route_label_score"],
            "route_label_reason": label_info["route_label_reason"],
            "query": query,
            "code": row["code"],
            "generated_query_operation": features.query_operation,
            "generated_query_domain": features.query_domain,
            "generated_code_domain": features.code_domain,
            "estimated_input_tokens": features.estimated_input_tokens,
            "requires_code": int(features.requires_code),
            "requires_tools": int(features.requires_tools),
        }
        output_row.update(flatten_features(features.values))
        output_rows.append(output_row)
        if args.progress_every and index % args.progress_every == 0:
            print(f"built {index}/{len(rows)}", flush=True)

    csv_path = args.output_dir / "router_training_trusted_v1.csv"
    jsonl_path = args.output_dir / "router_training_trusted_v1.jsonl"
    write_csv(csv_path, output_rows)
    write_jsonl(jsonl_path, output_rows)
    report = {
        "input": str(args.input),
        "csv": str(csv_path),
        "jsonl": str(jsonl_path),
        "rows": len(output_rows),
        "feature_columns": sum(
            1 for name in output_rows[0] if name.startswith("feature.")
        ) if output_rows else 0,
        "route_label_counts": Counter(row["route_label"] for row in output_rows),
        "split_counts": Counter(row["split"] for row in output_rows),
        "ambiguous_route_labels": sum(
            int(row["route_label_ambiguous"]) for row in output_rows
        ),
        "route_labels": list(ROUTE_LABELS),
    }
    args.output_dir.mkdir(parents=True, exist_ok=True)
    (args.output_dir / "router_training_report.json").write_text(
        json.dumps(report, indent=2),
        encoding="utf-8",
    )
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
